

annualpreci<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\annualpreci.asc")
avdailypreci_2018<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\avdailypreci_2018.asc")
avpreci10years<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\avpreci10years.asc")
elevation<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\elevation.asc")
maxtemperature<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\maxtemperature.asc")
meantempcoldquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\meantempcoldquarter.asc")
meantempdriestqtr<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\meantempdriestqtr.asc")
meantempwarmquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\meantempwarmquarter.asc")
meantempwettestqtr<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\meantempwettestqtr.asc")
mintemperature<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\mintemperature.asc")
precicoldestquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\precicoldestquarter.asc")
precidriestquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\precidriestquarter.asc")
preciwarmestquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\preciwarmestquarter.asc")
preciwettestquarter<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\preciwettestquarter.asc")
road_prox<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\road_prox.asc")
rwandalandco<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\rwandalandco.asc")
tmax_10yrs<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\tmax_10yrs.asc")
tmax_2017<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\tmax_2017.asc")
tmin_10years<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\tmin_10years.asc")
tmin_2017<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\tmin_2017.asc")
windspeed<-raster("C:\\Users\\dell\\Documents\\WORK\\Analysis2022\\BXWSDM\\data\\Environmental\\current old data\\windspeed.asc")

#calculate mean
cellStats(annualpreci, 'mean')
cellStats(avdailypreci_2018, 'mean')
cellStats(elevation, 'mean')
cellStats(avpreci10years, 'mean')
cellStats(maxtemperature, 'mean')
cellStats(meantempcoldquarter, 'mean')
cellStats(meantempdriestqtr, 'mean')
cellStats(meantempwarmquarter, 'mean')
cellStats(meantempwettestqtr, 'mean')
cellStats(mintemperature, 'mean')
cellStats(precicoldestquarter, 'mean')
cellStats(precidriestquarter, 'mean')
cellStats(preciwarmestquarter, 'mean')
cellStats(preciwettestquarter, 'mean')
cellStats(road_prox, 'mean')
cellStats(rwandalandco, 'mean')
cellStats(tmax_10yrs, 'mean')
cellStats(tmax_2017, 'mean')
cellStats(tmin_10years, 'mean')
cellStats(tmin_2017, 'mean')
cellStats(windspeed, 'mean')


#calculate sd
cellStats(annualpreci, 'sd')
cellStats(avdailypreci_2018, 'sd')
cellStats(elevation, 'sd')
cellStats(avpreci10years, 'sd')
cellStats(maxtemperature, 'sd')
cellStats(meantempcoldquarter, 'sd')
cellStats(meantempdriestqtr, 'sd')
cellStats(meantempwarmquarter, 'sd')
cellStats(meantempwettestqtr, 'sd')
cellStats(mintemperature, 'sd')
cellStats(precicoldestquarter, 'sd')
cellStats(precidriestquarter, 'sd')
cellStats(preciwarmestquarter, 'sd')
cellStats(preciwettestquarter, 'sd')
cellStats(road_prox, 'sd')
cellStats(rwandalandco, 'sd')
cellStats(tmax_10yrs, 'sd')
cellStats(tmax_2017, 'sd')
cellStats(tmin_10years, 'sd')
cellStats(tmin_2017, 'sd')
cellStats(windspeed, 'sd')
