on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Build image
      run: docker build -t main . 
     - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{secrets.TOKEN}} 
          -e SECRET=${{secrets.SECRET}} 
          -e MASTERNAME=${{secrets.MASTER_NAME}} 
          main
