on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
     
      - name: Install dependencies
        run: |
          install.packages("rsconnect", repos = "http://cran.us.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'bxwsurveillance')
        shell: Rscript {0}
