on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
    
      
      - name: Install dependencies
        run: |
          install.packages("rsconnect", repos = "http://cran.us.r-project.org")
          install.packages("shiny", repos = "http://cran.us.r-project.org")
          
          install.packages("units", repos = "http://cran.us.r-project.org") 
          install.packages("remotes", repos="http://cran.us.r-project.org")
          install.packages("sp", repos="http://cran.us.r-project.org")
          
          
          install.packages(c('Cairo','tidyr', 'tidyverse', 'zoo','grDevices', 'ggplot2',  'latticeExtra',  'lubridate', 'magrittr', 'httr','jsonlite','magrittr','tools','dplyr',
                   'naniar', 'plotly', 'png',   'rmarkdown', 'scales', 'shiny', 'shinyjs','shinyWidgets','raster','sf','tidyverse','gstat','leaflet','mapview'
                    ), repos = "http://cran.us.r-project.org")
          
          
        shell: Rscript {0}
        
      - name: Import data
        run: Rscript -e 'source("firebaseimport.R")'
        
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'bxwsurveillancettF',forceUpdate = TRUE)
          
          install.packages('cronR', repos = "http://cran.us.r-project.org")
          r <- cronR::cron_rscript("Incidence sms alert/Alert_sectors_clean.R")
          r2 <- cronR::cron_rscript("firebaseimport.R")
          cronR::cron_add(r, frequency = 'monthly', id = 'job_1', at = '01:00', days_of_month = 'first', days_of_week = '*', description = "update_data", ask = FALSE)
          cronR::cron_add(r2, frequency = "daily", id="job_2", at = "00:00", description = "fire_data_update", ask = FALSE)
          
        shell: Rscript {0}
     
     